# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    Modules\:
        resource: '../modules/'

    Prometheus\CollectorRegistry:
        alias: 'prometheus_metrics_bundle.collector_registry'

    Modules\Hunting\Domain\Repository\GuideRepositoryInterface:
        alias: Modules\Hunting\Infrastructure\Doctrine\Repository\DoctrineGuideRepository

    Modules\Hunting\Domain\Repository\BookingRepositoryInterface:
        alias: Modules\Hunting\Infrastructure\Doctrine\Repository\DoctrineBookingRepository

    Modules\Hunting\Application\Service\Guide\GuideServiceInterface:
        alias: Modules\Hunting\Application\Service\Guide\GuideService

    Modules\Hunting\Application\Service\Booking\HuntingBookingServiceInterface:
        alias: Modules\Hunting\Application\Service\Booking\HuntingBookingService

    Modules\Hunting\Application\Metrics\BookingMetricsInterface:
        alias: Modules\Hunting\Infrastructure\Metrics\PrometheusBookingMetrics

    Modules\Hunting\Application\Metrics\GuideMetricsInterface:
        alias: Modules\Hunting\Infrastructure\Metrics\PrometheusGuideMetrics

    Modules\Hunting\Application\Service\Booking\HuntingBookingServiceMetricsDecorator:
        decorates: Modules\Hunting\Application\Service\Booking\HuntingBookingService
        arguments:
            $inner: '@Modules\Hunting\Application\Service\Booking\HuntingBookingServiceMetricsDecorator.inner'

    Modules\Hunting\Application\Service\Guide\GuideServiceMetricsDecorator:
        decorates: Modules\Hunting\Application\Service\Guide\GuideService
        arguments:
            $inner: '@Modules\Hunting\Application\Service\Guide\GuideServiceMetricsDecorator.inner'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
