global:
    scrape_interval: 5s
    evaluation_interval: 5s

scrape_configs:
    - job_name: "symfony-api"
      metrics_path: /metrics/prometheus
      static_configs:
          - targets:
                - "nginx:80"
            labels:
                service: "symfony-api"
